/* Shared LC French vocab data — used by vocab.html and flashcards.html */
(function() {
  window.VOCAB = [
    /* ENVIRONMENT */
    { theme: 'environment', fr: 'le réchauffement climatique', pos: 'n.m.', en: 'global warming / climate change' },
    { theme: 'environment', fr: 'la sécheresse', pos: 'n.f.', en: 'drought' },
    { theme: 'environment', fr: 'les inondations', pos: 'n.f.pl.', en: 'floods' },
    { theme: 'environment', fr: 'l\'effet de serre', pos: 'n.m.', en: 'the greenhouse effect' },
    { theme: 'environment', fr: 'les gaz à effet de serre', pos: 'n.m.pl.', en: 'greenhouse gases' },
    { theme: 'environment', fr: 'la déforestation', pos: 'n.f.', en: 'deforestation' },
    { theme: 'environment', fr: 'la biodiversité', pos: 'n.f.', en: 'biodiversity' },
    { theme: 'environment', fr: 'les énergies renouvelables', pos: 'n.f.pl.', en: 'renewable energy' },
    { theme: 'environment', fr: 'l\'énergie solaire', pos: 'n.f.', en: 'solar energy' },
    { theme: 'environment', fr: 'l\'énergie éolienne', pos: 'n.f.', en: 'wind energy' },
    { theme: 'environment', fr: 'les émissions de carbone', pos: 'n.f.pl.', en: 'carbon emissions' },
    { theme: 'environment', fr: 'la pollution', pos: 'n.f.', en: 'pollution' },
    { theme: 'environment', fr: 'durable', pos: 'adj.', en: 'sustainable' },
    { theme: 'environment', fr: 'le développement durable', pos: 'n.m.', en: 'sustainable development' },
    { theme: 'environment', fr: 'recycler', pos: 'v.', en: 'to recycle' },
    { theme: 'environment', fr: 'la catastrophe naturelle', pos: 'n.f.', en: 'natural disaster' },
    { theme: 'environment', fr: 'la couche d\'ozone', pos: 'n.f.', en: 'the ozone layer' },
    { theme: 'environment', fr: 'la fonte des glaces', pos: 'n.f.', en: 'melting of the ice caps' },
    { theme: 'environment', fr: 'préserver', pos: 'v.', en: 'to preserve / protect' },
    { theme: 'environment', fr: 'menacer', pos: 'v.', en: 'to threaten' },

    /* TECHNOLOGY */
    { theme: 'technology', fr: 'les réseaux sociaux', pos: 'n.m.pl.', en: 'social networks / social media' },
    { theme: 'technology', fr: 'la technologie', pos: 'n.f.', en: 'technology' },
    { theme: 'technology', fr: 'l\'intelligence artificielle', pos: 'n.f.', en: 'artificial intelligence (AI)' },
    { theme: 'technology', fr: 'le numérique', pos: 'n.m.', en: 'the digital world' },
    { theme: 'technology', fr: 'un téléphone portable', pos: 'n.m.', en: 'a mobile phone' },
    { theme: 'technology', fr: 'naviguer sur Internet', pos: 'v. expr.', en: 'to browse the Internet' },
    { theme: 'technology', fr: 'télécharger', pos: 'v.', en: 'to download' },
    { theme: 'technology', fr: 'un écran', pos: 'n.m.', en: 'a screen' },
    { theme: 'technology', fr: 'le cyberharcèlement', pos: 'n.m.', en: 'cyberbullying' },
    { theme: 'technology', fr: 'les données personnelles', pos: 'n.f.pl.', en: 'personal data' },
    { theme: 'technology', fr: 'une application', pos: 'n.f.', en: 'an app / application' },
    { theme: 'technology', fr: 'un algorithme', pos: 'n.m.', en: 'an algorithm' },
    { theme: 'technology', fr: 'la désinformation', pos: 'n.f.', en: 'disinformation / fake news' },
    { theme: 'technology', fr: 'la dépendance', pos: 'n.f.', en: 'addiction / dependence' },
    { theme: 'technology', fr: 'un robot', pos: 'n.m.', en: 'a robot' },
    { theme: 'technology', fr: 'l\'automatisation', pos: 'n.f.', en: 'automation' },
    { theme: 'technology', fr: 'innovant(e)', pos: 'adj.', en: 'innovative' },
    { theme: 'technology', fr: 'le temps d\'écran', pos: 'n.m.', en: 'screen time' },
    { theme: 'technology', fr: 'une plateforme', pos: 'n.f.', en: 'a platform' },
    { theme: 'technology', fr: 'la vie privée', pos: 'n.f.', en: 'privacy / private life' },

    /* FAMILY */
    { theme: 'family', fr: 'les liens familiaux', pos: 'n.m.pl.', en: 'family ties' },
    { theme: 'family', fr: 'la famille monoparentale', pos: 'n.f.', en: 'single-parent family' },
    { theme: 'family', fr: 'la famille recomposée', pos: 'n.f.', en: 'blended / step family' },
    { theme: 'family', fr: 'le foyer', pos: 'n.m.', en: 'the home / household' },
    { theme: 'family', fr: 'l\'éducation', pos: 'n.f.', en: 'upbringing / education' },
    { theme: 'family', fr: 'les valeurs', pos: 'n.f.pl.', en: 'values' },
    { theme: 'family', fr: 'le soutien', pos: 'n.m.', en: 'support' },
    { theme: 'family', fr: 'l\'autonomie', pos: 'n.f.', en: 'independence / autonomy' },
    { theme: 'family', fr: 'une dispute', pos: 'n.f.', en: 'an argument / dispute' },
    { theme: 'family', fr: 'se réconcilier', pos: 'v.', en: 'to make up / reconcile' },
    { theme: 'family', fr: 'la solidarité', pos: 'n.f.', en: 'solidarity' },
    { theme: 'family', fr: 'élever', pos: 'v.', en: 'to raise (a child)' },
    { theme: 'family', fr: 'partager', pos: 'v.', en: 'to share' },
    { theme: 'family', fr: 'le déménagement', pos: 'n.m.', en: 'moving house' },
    { theme: 'family', fr: 'la tradition', pos: 'n.f.', en: 'tradition' },
    { theme: 'family', fr: 'l\'héritage', pos: 'n.m.', en: 'heritage / inheritance' },
    { theme: 'family', fr: 'la confiance', pos: 'n.f.', en: 'trust / confidence' },
    { theme: 'family', fr: 'les proches', pos: 'n.m.pl.', en: 'loved ones / close family' },
    { theme: 'family', fr: 'entretenir', pos: 'v.', en: 'to maintain (a relationship)' },
    { theme: 'family', fr: 'le divorce', pos: 'n.m.', en: 'divorce' },

    /* WORK & STUDY */
    { theme: 'work', fr: 'le marché du travail', pos: 'n.m.', en: 'the job market / labour market' },
    { theme: 'work', fr: 'le chômage', pos: 'n.m.', en: 'unemployment' },
    { theme: 'work', fr: 'un emploi', pos: 'n.m.', en: 'a job / employment' },
    { theme: 'work', fr: 'un stage', pos: 'n.m.', en: 'an internship / work placement' },
    { theme: 'work', fr: 'le salaire', pos: 'n.m.', en: 'salary / wage' },
    { theme: 'work', fr: 'le télétravail', pos: 'n.m.', en: 'remote working / working from home' },
    { theme: 'work', fr: 'l\'équilibre vie pro/vie perso', pos: 'n.m.', en: 'work-life balance' },
    { theme: 'work', fr: 'la formation', pos: 'n.f.', en: 'training / education / course' },
    { theme: 'work', fr: 'le baccalauréat', pos: 'n.m.', en: 'the Baccalaureate (leaving exam)' },
    { theme: 'work', fr: 'les études supérieures', pos: 'n.f.pl.', en: 'higher education' },
    { theme: 'work', fr: 'une carrière', pos: 'n.f.', en: 'a career' },
    { theme: 'work', fr: 'postuler à', pos: 'v.', en: 'to apply for' },
    { theme: 'work', fr: 'un entretien d\'embauche', pos: 'n.m.', en: 'a job interview' },
    { theme: 'work', fr: 'la retraite', pos: 'n.f.', en: 'retirement' },
    { theme: 'work', fr: 'les compétences', pos: 'n.f.pl.', en: 'skills / competencies' },
    { theme: 'work', fr: 'le burn-out', pos: 'n.m.', en: 'burnout' },
    { theme: 'work', fr: 'la grève', pos: 'n.f.', en: 'strike (industrial action)' },
    { theme: 'work', fr: 'un syndicat', pos: 'n.m.', en: 'a trade union' },
    { theme: 'work', fr: 'l\'égalité des chances', pos: 'n.f.', en: 'equal opportunities' },
    { theme: 'work', fr: 'embaucher', pos: 'v.', en: 'to hire / employ' },

    /* SOCIETY */
    { theme: 'society', fr: 'la citoyenneté', pos: 'n.f.', en: 'citizenship' },
    { theme: 'society', fr: 'le bénévolat', pos: 'n.m.', en: 'volunteering' },
    { theme: 'society', fr: 'l\'intégration', pos: 'n.f.', en: 'integration' },
    { theme: 'society', fr: 'l\'immigration', pos: 'n.f.', en: 'immigration' },
    { theme: 'society', fr: 'la pauvreté', pos: 'n.f.', en: 'poverty' },
    { theme: 'society', fr: 'les inégalités', pos: 'n.f.pl.', en: 'inequalities' },
    { theme: 'society', fr: 'la discrimination', pos: 'n.f.', en: 'discrimination' },
    { theme: 'society', fr: 'le racisme', pos: 'n.m.', en: 'racism' },
    { theme: 'society', fr: 'la banlieue', pos: 'n.f.', en: 'suburb / housing estate (French context)' },
    { theme: 'society', fr: 'la fracture sociale', pos: 'n.f.', en: 'social divide / inequality' },
    { theme: 'society', fr: 'les sans-abri', pos: 'n.m.pl.', en: 'homeless people' },
    { theme: 'society', fr: 'l\'exclusion sociale', pos: 'n.f.', en: 'social exclusion' },
    { theme: 'society', fr: 'le vivre-ensemble', pos: 'n.m.', en: 'living together / community cohesion' },
    { theme: 'society', fr: 'la laïcité', pos: 'n.f.', en: 'secularism / separation of church and state' },
    { theme: 'society', fr: 'la démocratie', pos: 'n.f.', en: 'democracy' },
    { theme: 'society', fr: 'les droits de l\'homme', pos: 'n.m.pl.', en: 'human rights' },
    { theme: 'society', fr: 's\'engager', pos: 'v.', en: 'to commit / get involved' },
    { theme: 'society', fr: 'la manifestation', pos: 'n.f.', en: 'demonstration / protest' },
    { theme: 'society', fr: 'sensibiliser', pos: 'v.', en: 'to raise awareness' },
    { theme: 'society', fr: 'lutter contre', pos: 'v. expr.', en: 'to fight / struggle against' },

    /* HEALTH */
    { theme: 'health', fr: 'la santé', pos: 'n.f.', en: 'health' },
    { theme: 'health', fr: 'le bien-être', pos: 'n.m.', en: 'well-being' },
    { theme: 'health', fr: 'l\'alimentation', pos: 'n.f.', en: 'diet / food / eating habits' },
    { theme: 'health', fr: 'équilibré(e)', pos: 'adj.', en: 'balanced' },
    { theme: 'health', fr: 'l\'obésité', pos: 'n.f.', en: 'obesity' },
    { theme: 'health', fr: 'la maladie', pos: 'n.f.', en: 'illness / disease' },
    { theme: 'health', fr: 'la médecine', pos: 'n.f.', en: 'medicine' },
    { theme: 'health', fr: 'le système de santé', pos: 'n.m.', en: 'the health system' },
    { theme: 'health', fr: 'l\'hôpital', pos: 'n.m.', en: 'hospital' },
    { theme: 'health', fr: 'un médecin', pos: 'n.m.', en: 'a doctor (GP)' },
    { theme: 'health', fr: 'le stress', pos: 'n.m.', en: 'stress' },
    { theme: 'health', fr: 'la dépression', pos: 'n.f.', en: 'depression' },
    { theme: 'health', fr: 'la santé mentale', pos: 'n.f.', en: 'mental health' },
    { theme: 'health', fr: 'faire de l\'exercice', pos: 'v. expr.', en: 'to exercise' },
    { theme: 'health', fr: 'l\'alcool', pos: 'n.m.', en: 'alcohol' },
    { theme: 'health', fr: 'le tabac', pos: 'n.m.', en: 'tobacco / smoking' },
    { theme: 'health', fr: 'bio / biologique', pos: 'adj.', en: 'organic' },
    { theme: 'health', fr: 'prévenir', pos: 'v.', en: 'to prevent' },
    { theme: 'health', fr: 'guérir', pos: 'v.', en: 'to cure / heal / recover' },
    { theme: 'health', fr: 'l\'espérance de vie', pos: 'n.f.', en: 'life expectancy' },

    /* TRAVEL */
    { theme: 'travel', fr: 'un voyage', pos: 'n.m.', en: 'a journey / trip' },
    { theme: 'travel', fr: 'un séjour', pos: 'n.m.', en: 'a stay / visit' },
    { theme: 'travel', fr: 'les vacances', pos: 'n.f.pl.', en: 'holidays / vacation' },
    { theme: 'travel', fr: 'à l\'étranger', pos: 'adv.', en: 'abroad' },
    { theme: 'travel', fr: 'le tourisme', pos: 'n.m.', en: 'tourism' },
    { theme: 'travel', fr: 'un touriste', pos: 'n.m.', en: 'a tourist' },
    { theme: 'travel', fr: 'dépayser', pos: 'v.', en: 'to take sb out of their element' },
    { theme: 'travel', fr: 'le dépaysement', pos: 'n.m.', en: 'the feeling of being in a new place' },
    { theme: 'travel', fr: 's\'adapter', pos: 'v.', en: 'to adapt' },
    { theme: 'travel', fr: 'découvrir', pos: 'v.', en: 'to discover' },
    { theme: 'travel', fr: 'une auberge de jeunesse', pos: 'n.f.', en: 'a youth hostel' },
    { theme: 'travel', fr: 'le patrimoine', pos: 'n.m.', en: 'heritage / cultural heritage' },
    { theme: 'travel', fr: 'se dépayser', pos: 'v.', en: 'to have a change of scene' },
    { theme: 'travel', fr: 'l\'aventure', pos: 'n.f.', en: 'adventure' },
    { theme: 'travel', fr: 'une escale', pos: 'n.f.', en: 'a stopover' },
    { theme: 'travel', fr: 'les transports en commun', pos: 'n.m.pl.', en: 'public transport' },
    { theme: 'travel', fr: 'l\'empreinte carbone', pos: 'n.f.', en: 'carbon footprint' },
    { theme: 'travel', fr: 'un circuit', pos: 'n.m.', en: 'a tour / route' },
    { theme: 'travel', fr: 'insolite', pos: 'adj.', en: 'unusual / out of the ordinary' },
    { theme: 'travel', fr: 'dépenser', pos: 'v.', en: 'to spend (money)' },

    /* MEDIA */
    { theme: 'media', fr: 'les médias', pos: 'n.m.pl.', en: 'the media' },
    { theme: 'media', fr: 'un journal', pos: 'n.m.', en: 'a newspaper' },
    { theme: 'media', fr: 'une émission', pos: 'n.f.', en: 'a programme / broadcast' },
    { theme: 'media', fr: 'l\'actualité', pos: 'n.f.', en: 'current events / the news' },
    { theme: 'media', fr: 'un reportage', pos: 'n.m.', en: 'a report / documentary' },
    { theme: 'media', fr: 'la presse', pos: 'n.f.', en: 'the press' },
    { theme: 'media', fr: 'la liberté de la presse', pos: 'n.f.', en: 'freedom of the press' },
    { theme: 'media', fr: 'un journaliste', pos: 'n.m.', en: 'a journalist' },
    { theme: 'media', fr: 'diffuser', pos: 'v.', en: 'to broadcast / spread' },
    { theme: 'media', fr: 'une fake news', pos: 'n.f.', en: 'fake news / misinformation' },
    { theme: 'media', fr: 'l\'influence', pos: 'n.f.', en: 'influence' },
    { theme: 'media', fr: 'un influenceur', pos: 'n.m.', en: 'an influencer' },
    { theme: 'media', fr: 'le streaming', pos: 'n.m.', en: 'streaming' },
    { theme: 'media', fr: 'censurer', pos: 'v.', en: 'to censor' },
    { theme: 'media', fr: 'la publicité', pos: 'n.f.', en: 'advertising / an advert' },
    { theme: 'media', fr: 'manipuler', pos: 'v.', en: 'to manipulate' },
    { theme: 'media', fr: 'une chaîne de télévision', pos: 'n.f.', en: 'a TV channel' },
    { theme: 'media', fr: 'l\'opinion publique', pos: 'n.f.', en: 'public opinion' },
    { theme: 'media', fr: 'informer', pos: 'v.', en: 'to inform' },
    { theme: 'media', fr: 'un abonné', pos: 'n.m.', en: 'a subscriber / follower' },

    /* SPORT */
    { theme: 'sport', fr: 'le sport', pos: 'n.m.', en: 'sport' },
    { theme: 'sport', fr: 'une équipe', pos: 'n.f.', en: 'a team' },
    { theme: 'sport', fr: 'un entraîneur', pos: 'n.m.', en: 'a coach / trainer' },
    { theme: 'sport', fr: 'la compétition', pos: 'n.f.', en: 'competition' },
    { theme: 'sport', fr: 'un champion / une championne', pos: 'n.', en: 'a champion' },
    { theme: 'sport', fr: 'gagner', pos: 'v.', en: 'to win' },
    { theme: 'sport', fr: 'perdre', pos: 'v.', en: 'to lose' },
    { theme: 'sport', fr: 'un match', pos: 'n.m.', en: 'a match / game' },
    { theme: 'sport', fr: 'les Jeux Olympiques', pos: 'n.m.pl.', en: 'the Olympic Games' },
    { theme: 'sport', fr: 'le dopage', pos: 'n.m.', en: 'doping / drug use in sport' },
    { theme: 'sport', fr: 'la performance', pos: 'n.f.', en: 'performance' },
    { theme: 'sport', fr: 's\'entraîner', pos: 'v.', en: 'to train / practise' },
    { theme: 'sport', fr: 'la forme physique', pos: 'n.f.', en: 'physical fitness' },
    { theme: 'sport', fr: 'un stade', pos: 'n.m.', en: 'a stadium' },
    { theme: 'sport', fr: 'le fair-play', pos: 'n.m.', en: 'fair play / sportsmanship' },
    { theme: 'sport', fr: 'blesser / une blessure', pos: 'v. / n.f.', en: 'to injure / an injury' },
    { theme: 'sport', fr: 'professionnel(le)', pos: 'adj.', en: 'professional' },
    { theme: 'sport', fr: 'le spectateur', pos: 'n.m.', en: 'spectator / fan' },
    { theme: 'sport', fr: 'le palmarès', pos: 'n.m.', en: 'list of achievements / track record' },
    { theme: 'sport', fr: 'la rivalité', pos: 'n.f.', en: 'rivalry' },

    /* HOME */
    { theme: 'home', fr: 'une maison mitoyenne', pos: 'n.f.', en: 'terraced house' },
    { theme: 'home', fr: 'une maison jumelée', pos: 'n.f.', en: 'semi-detached house' },
    { theme: 'home', fr: 'une maison individuelle', pos: 'n.f.', en: 'detached house' },
    { theme: 'home', fr: 'un appartement', pos: 'n.m.', en: 'a flat / apartment' },
    { theme: 'home', fr: 'un immeuble', pos: 'n.m.', en: 'an apartment block' },
    { theme: 'home', fr: 'une HLM', pos: 'n.f.', en: 'social / council housing' },
    { theme: 'home', fr: 'la banlieue', pos: 'n.f.', en: 'suburb / outskirts' },
    { theme: 'home', fr: 'le centre-ville', pos: 'n.m.', en: 'city centre / town centre' },
    { theme: 'home', fr: 'le lotissement', pos: 'n.m.', en: 'housing estate' },
    { theme: 'home', fr: 'la cuisine', pos: 'n.f.', en: 'kitchen' },
    { theme: 'home', fr: 'la salle de séjour', pos: 'n.f.', en: 'sitting room / lounge' },
    { theme: 'home', fr: 'la salle de bains', pos: 'n.f.', en: 'bathroom' },
    { theme: 'home', fr: 'la chambre', pos: 'n.f.', en: 'bedroom' },
    { theme: 'home', fr: 'le grenier', pos: 'n.m.', en: 'attic' },
    { theme: 'home', fr: 'le canapé', pos: 'n.m.', en: 'sofa / couch' },
    { theme: 'home', fr: 'l\'armoire', pos: 'n.f.', en: 'wardrobe' },
    { theme: 'home', fr: 'les espaces verts', pos: 'n.m.pl.', en: 'green spaces / parks' },
    { theme: 'home', fr: 'les embouteillages', pos: 'n.m.pl.', en: 'traffic jams' },
    { theme: 'home', fr: 'les cambriolages', pos: 'n.m.pl.', en: 'burglaries' },
    { theme: 'home', fr: 'la délinquance', pos: 'n.f.', en: 'delinquency / antisocial behaviour' },

    /* SCHOOL */
    { theme: 'school', fr: 'l\'école maternelle', pos: 'n.f.', en: 'nursery school' },
    { theme: 'school', fr: 'l\'école primaire', pos: 'n.f.', en: 'primary school' },
    { theme: 'school', fr: 'le collège', pos: 'n.m.', en: 'junior secondary school (France)' },
    { theme: 'school', fr: 'le lycée', pos: 'n.m.', en: 'senior secondary school (France)' },
    { theme: 'school', fr: 'obligatoire', pos: 'adj.', en: 'compulsory / mandatory' },
    { theme: 'school', fr: 'le baccalauréat', pos: 'n.m.', en: 'French school leaving exam (Leaving Cert equivalent)' },
    { theme: 'school', fr: 'réussir un examen', pos: 'v. expr.', en: 'to pass an exam' },
    { theme: 'school', fr: 'rater un examen', pos: 'v. expr.', en: 'to fail an exam' },
    { theme: 'school', fr: 'une matière', pos: 'n.f.', en: 'a school subject' },
    { theme: 'school', fr: 'un(e) élève', pos: 'n.', en: 'a secondary school pupil' },
    { theme: 'school', fr: 'un(e) étudiant(e)', pos: 'n.', en: 'a university student' },
    { theme: 'school', fr: 'un(e) enseignant(e)', pos: 'n.', en: 'a teacher' },
    { theme: 'school', fr: 'être collé(e)', pos: 'v. expr.', en: 'to get detention' },
    { theme: 'school', fr: 'être renvoyé(e)', pos: 'v. expr.', en: 'to be expelled' },
    { theme: 'school', fr: 'la rentrée', pos: 'n.f.', en: 'return to school / start of school year' },
    { theme: 'school', fr: 'les examens blancs', pos: 'n.m.pl.', en: 'mock exams' },
    { theme: 'school', fr: 'un échange scolaire', pos: 'n.m.', en: 'a school exchange' },
    { theme: 'school', fr: 'l\'enseignement supérieur', pos: 'n.m.', en: 'higher education' },
    { theme: 'school', fr: 'faire un stage', pos: 'v. expr.', en: 'to do work experience' },
    { theme: 'school', fr: 'prendre une année sabbatique', pos: 'v. expr.', en: 'to take a gap year' },
    { theme: 'school', fr: 'respecter le règlement', pos: 'v. expr.', en: 'to follow the school rules' },
    { theme: 'school', fr: 'travailler comme bénévole', pos: 'v. expr.', en: 'to work as a volunteer' },

    /* YOUTH */
    { theme: 'youth', fr: 'attentionné(e)', pos: 'adj.', en: 'caring / thoughtful' },
    { theme: 'youth', fr: 'loyal(e)', pos: 'adj.', en: 'loyal' },
    { theme: 'youth', fr: 'compréhensif/compréhensive', pos: 'adj.', en: 'understanding' },
    { theme: 'youth', fr: 'égoïste', pos: 'adj.', en: 'selfish' },
    { theme: 'youth', fr: 'jaloux/jalouse', pos: 'adj.', en: 'jealous' },
    { theme: 'youth', fr: 'malhonnête', pos: 'adj.', en: 'dishonest' },
    { theme: 'youth', fr: 'têtu(e)', pos: 'adj.', en: 'stubborn' },
    { theme: 'youth', fr: 'branché(e)', pos: 'adj.', en: 'trendy' },
    { theme: 'youth', fr: 'démodé(e)', pos: 'adj.', en: 'old-fashioned / out of style' },
    { theme: 'youth', fr: 'une tendance', pos: 'n.f.', en: 'a trend' },
    { theme: 'youth', fr: 'être à la mode', pos: 'v. expr.', en: 'to be fashionable / in style' },
    { theme: 'youth', fr: 'l\'argent de poche', pos: 'n.m.', en: 'pocket money' },
    { theme: 'youth', fr: 'économiser', pos: 'v.', en: 'to save money' },
    { theme: 'youth', fr: 'dépenser', pos: 'v.', en: 'to spend money' },
    { theme: 'youth', fr: 'être à découvert', pos: 'v. expr.', en: 'to be overdrawn / broke' },
    { theme: 'youth', fr: 'un boulot d\'été', pos: 'n.m.', en: 'a summer job' },
    { theme: 'youth', fr: 'travailler à temps partiel', pos: 'v. expr.', en: 'to work part-time' },
    { theme: 'youth', fr: 'gagner le SMIC', pos: 'v. expr.', en: 'to earn minimum wage' },
    { theme: 'youth', fr: 'un manteau', pos: 'n.m.', en: 'a coat' },
    { theme: 'youth', fr: 'un survêtement', pos: 'n.m.', en: 'a tracksuit' },
    { theme: 'youth', fr: 'sortir en boîte', pos: 'v. expr.', en: 'to go clubbing' },
    { theme: 'youth', fr: 'faire du shopping', pos: 'v. expr.', en: 'to go shopping' },

    /* LEISURE */
    { theme: 'leisure', fr: 'les loisirs', pos: 'n.m.pl.', en: 'leisure activities / pastimes' },
    { theme: 'leisure', fr: 'un passe-temps', pos: 'n.m.', en: 'a hobby / pastime' },
    { theme: 'leisure', fr: 'bouquiner', pos: 'v.', en: 'to read (informal)' },
    { theme: 'leisure', fr: 'tenir un blog', pos: 'v. expr.', en: 'to keep a blog' },
    { theme: 'leisure', fr: 'télécharger de la musique', pos: 'v. expr.', en: 'to download music' },
    { theme: 'leisure', fr: 'la lecture', pos: 'n.f.', en: 'reading' },
    { theme: 'leisure', fr: 'la peinture', pos: 'n.f.', en: 'painting' },
    { theme: 'leisure', fr: 'le jardinage', pos: 'n.m.', en: 'gardening' },
    { theme: 'leisure', fr: 'faire la grasse matinée', pos: 'v. expr.', en: 'to have a lie-in' },
    { theme: 'leisure', fr: 'des randonnées', pos: 'n.f.pl.', en: 'hikes / countryside walks' },
    { theme: 'leisure', fr: 'le lèche-vitrine', pos: 'n.m.', en: 'window shopping' },
    { theme: 'leisure', fr: 'un roman', pos: 'n.m.', en: 'a novel' },
    { theme: 'leisure', fr: 'une bande dessinée', pos: 'n.f.', en: 'a comic strip / graphic novel' },
    { theme: 'leisure', fr: 'se défouler', pos: 'v. expr.', en: 'to let off steam' },
    { theme: 'leisure', fr: 'se détendre', pos: 'v.', en: 'to relax / unwind' },
    { theme: 'leisure', fr: 'un(e) cinéphile', pos: 'n.', en: 'a cinema / film lover' },
    { theme: 'leisure', fr: 'mélomane', pos: 'n./adj.', en: 'a music lover' },
    { theme: 'leisure', fr: 'la chorale', pos: 'n.f.', en: 'the choir' },

    /* FAMILY — extended */
    { theme: 'family', fr: 's\'entendre bien avec', pos: 'v. expr.', en: 'to get on well with' },
    { theme: 'family', fr: 'se disputer avec', pos: 'v. expr.', en: 'to argue / fight with' },
    { theme: 'family', fr: 'être comme chien et chat', pos: 'expr.', en: 'to fight like cat and dog' },
    { theme: 'family', fr: 'avoir confiance en', pos: 'v. expr.', en: 'to trust someone' },
    { theme: 'family', fr: 'se soutenir', pos: 'v. expr.', en: 'to support each other' },
    { theme: 'family', fr: 'débarrasser la table', pos: 'v. expr.', en: 'to clear the table' },
    { theme: 'family', fr: 'faire la lessive', pos: 'v. expr.', en: 'to do the laundry' },
    { theme: 'family', fr: 'passer l\'aspirateur', pos: 'v. expr.', en: 'to hoover' },
    { theme: 'family', fr: 'ranger sa chambre', pos: 'v. expr.', en: 'to tidy one\'s room' },
    { theme: 'family', fr: 'le harcèlement sexuel', pos: 'n.m.', en: 'sexual harassment' },
    { theme: 'family', fr: 'la violence conjugale', pos: 'n.f.', en: 'domestic violence' },
    { theme: 'family', fr: 'l\'émancipation des femmes', pos: 'n.f.', en: 'female emancipation' },

    /* TRAVEL — extended */
    { theme: 'travel', fr: 'les grandes vacances', pos: 'n.f.pl.', en: 'summer holidays' },
    { theme: 'travel', fr: 'séjourner', pos: 'v.', en: 'to stay (in a place)' },
    { theme: 'travel', fr: 'une station de ski', pos: 'n.f.', en: 'a ski resort' },
    { theme: 'travel', fr: 'une station balnéaire', pos: 'n.f.', en: 'a seaside resort' },
    { theme: 'travel', fr: 'au bord de la mer', pos: 'adv.', en: 'beside the sea' },
    { theme: 'travel', fr: 'réserver les billets', pos: 'v. expr.', en: 'to book tickets' },
    { theme: 'travel', fr: 'louer une voiture', pos: 'v. expr.', en: 'to rent a car' },
    { theme: 'travel', fr: 'un gîte', pos: 'n.m.', en: 'a holiday cottage' },
    { theme: 'travel', fr: 'une caravane', pos: 'n.f.', en: 'a caravan' },
    { theme: 'travel', fr: 'se faire bronzer', pos: 'v. expr.', en: 'to sunbathe' },
    { theme: 'travel', fr: 'partir en excursion', pos: 'v. expr.', en: 'to go on an excursion' },
    { theme: 'travel', fr: 'la canicule', pos: 'n.f.', en: 'a heatwave' },
    { theme: 'travel', fr: 'le brouillard', pos: 'n.m.', en: 'fog' },
    { theme: 'travel', fr: 'une tempête', pos: 'n.f.', en: 'a storm' },
    { theme: 'travel', fr: 'circuler', pos: 'v.', en: 'to get around / drive around' },

    /* HEALTH — extended */
    { theme: 'health', fr: 'avoir de la fièvre', pos: 'v. expr.', en: 'to have a fever' },
    { theme: 'health', fr: 'guérir', pos: 'v.', en: 'to recover / get better' },
    { theme: 'health', fr: 'se blesser', pos: 'v. expr.', en: 'to injure oneself' },
    { theme: 'health', fr: 'éternuer', pos: 'v.', en: 'to sneeze' },
    { theme: 'health', fr: 'tousser', pos: 'v.', en: 'to cough' },
    { theme: 'health', fr: 'vomir', pos: 'v.', en: 'to vomit' },
    { theme: 'health', fr: 'la grippe', pos: 'n.f.', en: 'flu' },
    { theme: 'health', fr: 'le rhume', pos: 'n.m.', en: 'a cold' },
    { theme: 'health', fr: 'les urgences', pos: 'n.f.pl.', en: 'A&E / emergency department' },
    { theme: 'health', fr: 'un médicament', pos: 'n.m.', en: 'a medication / medicine' },
    { theme: 'health', fr: 'une ordonnance', pos: 'n.f.', en: 'a prescription' },
    { theme: 'health', fr: 'surveiller sa ligne', pos: 'v. expr.', en: 'to watch one\'s figure' },
    { theme: 'health', fr: 'sauter un repas', pos: 'v. expr.', en: 'to skip a meal' },
    { theme: 'health', fr: 'être en surpoids', pos: 'adj./expr.', en: 'to be overweight' },
    { theme: 'health', fr: 'le tabagisme', pos: 'n.m.', en: 'smoking / nicotine addiction' },
    { theme: 'health', fr: 'la toxicomanie', pos: 'n.f.', en: 'drug addiction' },
    { theme: 'health', fr: 'boire à la défonce', pos: 'v. expr.', en: 'to binge drink' },
    { theme: 'health', fr: 'avoir la gueule de bois', pos: 'expr.', en: 'to have a hangover' },

    /* MEDIA — extended */
    { theme: 'media', fr: 'un quotidien', pos: 'n.m.', en: 'a daily newspaper' },
    { theme: 'media', fr: 'un hebdomadaire', pos: 'n.m.', en: 'a weekly magazine / paper' },
    { theme: 'media', fr: 'un abonnement', pos: 'n.m.', en: 'a subscription' },
    { theme: 'media', fr: 'le rédacteur en chef', pos: 'n.m.', en: 'the editor-in-chief' },
    { theme: 'media', fr: 'être à la une', pos: 'v. expr.', en: 'to be on the front page' },
    { theme: 'media', fr: 'une rubrique', pos: 'n.f.', en: 'a column / section (in a newspaper)' },
    { theme: 'media', fr: 'les infos', pos: 'n.f.pl.', en: 'the news (TV / radio)' },
    { theme: 'media', fr: 'en direct', pos: 'adv.', en: 'live' },
    { theme: 'media', fr: 'doubler', pos: 'v.', en: 'to dub (a film)' },
    { theme: 'media', fr: 'une station de radio', pos: 'n.f.', en: 'a radio station' },
    { theme: 'media', fr: 'à l\'antenne', pos: 'adv.', en: 'on air' },
    { theme: 'media', fr: 'la pub', pos: 'n.f.', en: 'advertising / an advert (informal)' },

    /* TECHNOLOGY — extended */
    { theme: 'technology', fr: 'Internet haut débit', pos: 'n.m.', en: 'broadband internet' },
    { theme: 'technology', fr: 'un site web', pos: 'n.m.', en: 'a website' },
    { theme: 'technology', fr: 'un moteur de recherche', pos: 'n.m.', en: 'a search engine' },
    { theme: 'technology', fr: 'tchatter en ligne', pos: 'v. expr.', en: 'to chat online' },
    { theme: 'technology', fr: 'un courriel', pos: 'n.m.', en: 'an email (formal French)' },
    { theme: 'technology', fr: 'la boîte de réception', pos: 'n.f.', en: 'the inbox' },
    { theme: 'technology', fr: 'graver un CD', pos: 'v. expr.', en: 'to burn a CD' },
    { theme: 'technology', fr: 'une clé USB', pos: 'n.f.', en: 'a USB key' },
    { theme: 'technology', fr: 'capter', pos: 'v.', en: 'to get signal / reception' },
    { theme: 'technology', fr: 'un chargeur', pos: 'n.m.', en: 'a charger' },

    /* SPORT — extended */
    { theme: 'sport', fr: 'l\'aviron', pos: 'n.m.', en: 'rowing' },
    { theme: 'sport', fr: 'l\'escrime', pos: 'n.f.', en: 'fencing' },
    { theme: 'sport', fr: 'l\'équitation', pos: 'n.f.', en: 'horse riding' },
    { theme: 'sport', fr: 'l\'athlétisme', pos: 'n.m.', en: 'athletics' },
    { theme: 'sport', fr: 'le cyclisme', pos: 'n.m.', en: 'cycling' },
    { theme: 'sport', fr: 'l\'escalade', pos: 'n.f.', en: 'climbing' },
    { theme: 'sport', fr: 'la natation', pos: 'n.f.', en: 'swimming' },
    { theme: 'sport', fr: 'le ski nautique', pos: 'n.m.', en: 'water skiing' },
    { theme: 'sport', fr: 'le surf des neiges', pos: 'n.m.', en: 'snowboarding' },
    { theme: 'sport', fr: 'le tir à l\'arc', pos: 'n.m.', en: 'archery' },
    { theme: 'sport', fr: 'le VTT', pos: 'n.m.', en: 'mountain biking' },
    { theme: 'sport', fr: 'l\'esprit d\'équipe', pos: 'n.m.', en: 'team spirit' },
  ];

  window.THEME_META = {
    environment: { label: 'Environment', icon: '🌿', iconBg: 'var(--sage-tint)', iconColor: 'var(--sage)' },
    technology:  { label: 'Technology',  icon: '💻', iconBg: 'var(--sky-soft)', iconColor: '#3a5b76' },
    family:      { label: 'Family',      icon: '🏠', iconBg: 'var(--rose-soft)', iconColor: '#8b3a2e' },
    work:        { label: 'Work &amp; Study', icon: '📋', iconBg: 'var(--butter-soft)', iconColor: '#8a6a0c' },
    society:     { label: 'Society',     icon: '🤝', iconBg: 'var(--lilac-soft)', iconColor: '#5a4a76' },
    health:      { label: 'Health',      icon: '❤️', iconBg: 'var(--rose-soft)', iconColor: '#8b3a2e' },
    travel:      { label: 'Travel',      icon: '✈️', iconBg: 'var(--sky-soft)', iconColor: '#3a5b76' },
    media:       { label: 'Media',       icon: '📰', iconBg: 'var(--bg-2)', iconColor: 'var(--ink)' },
    sport:       { label: 'Sport',       icon: '⚽', iconBg: 'var(--butter-soft)', iconColor: '#8a6a0c' },
    home:    { label: 'Home &amp; Area', icon: '🏡', iconBg: '#f3ede4', iconColor: '#6b5a45' },
    school:  { label: 'School',          icon: '📚', iconBg: 'var(--lilac-soft)', iconColor: '#5a4a76' },
    youth:   { label: 'Youth &amp; Life',icon: '🧑', iconBg: 'var(--rose-soft)', iconColor: '#8b3a2e' },
    leisure: { label: 'Leisure',         icon: '🎭', iconBg: 'var(--sage-tint)', iconColor: 'var(--sage)' },
  };
})();
